<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKics7c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKics7c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAKics7c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAKics7c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAKics7c\App_KernelDevDebugContainer([
    'container.build_hash' => 'AKics7c',
    'container.build_id' => 'ff739640',
    'container.build_time' => 1629050277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKics7c');
