<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], []],
    'shopList' => [[], ['_controller' => 'App\\Controller\\IndexController::shopList'], [], [['text', '/shop/list']], [], []],
    'shopCartAdd' => [['id'], ['_controller' => 'App\\Controller\\IndexController::shopCartAdd'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/shop/cart/add']], [], []],
    'shopCartDelete' => [['id'], ['_controller' => 'App\\Controller\\IndexController::shopCartDelete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/shop/cart/delete']], [], []],
    'shopItem' => [['id'], ['_controller' => 'App\\Controller\\IndexController::shopItem'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/shop/item']], [], []],
    'shopCart' => [[], ['_controller' => 'App\\Controller\\IndexController::shopCart'], [], [['text', '/shop/cart']], [], []],
    'shopOrder' => [[], ['_controller' => 'App\\Controller\\IndexController::shopOrder'], [], [['text', '/shop/order']], [], []],
];
