<?php

namespace ContainerZROvBxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NAhe9deService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NAhe9de' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NAhe9de'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itemsRepository' => ['privates', 'App\\Repository\\ShopItemsRepository', 'getShopItemsRepositoryService', true],
        ], [
            'itemsRepository' => 'App\\Repository\\ShopItemsRepository',
        ]);
    }
}
