<?php

namespace ContainerZROvBxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_It2NRj6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.it2NRj6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.it2NRj6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'shopCart' => ['privates', '.errored..service_locator.it2NRj6.App\\Entity\\ShopCart', NULL, 'Cannot autowire service ".service_locator.it2NRj6": it references class "App\\Entity\\ShopCart" but no such service exists.'],
        ], [
            'em' => '?',
            'shopCart' => 'App\\Entity\\ShopCart',
        ]);
    }
}
