<?php

namespace ContainerZROvBxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HaQC_ZgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.haQC.Zg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.haQC.Zg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'shopItems' => ['privates', '.errored..service_locator.haQC.Zg.App\\Entity\\ShopItems', NULL, 'Cannot autowire service ".service_locator.haQC.Zg": it references class "App\\Entity\\ShopItems" but no such service exists.'],
        ], [
            'shopItems' => 'App\\Entity\\ShopItems',
        ]);
    }
}
