<?php

namespace ContainerZROvBxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopItemsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZQIo_BP.App\Entity\ShopItems' shared service.
     *
     * @return \App\Entity\ShopItems
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZQIo_BP": it references class "App\\Entity\\ShopItems" but no such service exists.');
    }
}
