<?php

namespace ContainerZROvBxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopCartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.it2NRj6.App\Entity\ShopCart' shared service.
     *
     * @return \App\Entity\ShopCart
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.it2NRj6": it references class "App\\Entity\\ShopCart" but no such service exists.');
    }
}
